apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::210953236598:role/service-account-role
  name: alb-ingress-controller
  namespace: kube-system